# Generated by Django 4.1.2 on 2023-03-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_created_at_expense_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-updated_at']},
        ),
    ]
